name: Build
on:
  # NOTE: Runs on branch to tag creation.
  create:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell

      #- name: Install yarn
      #  run: npm install --global yarn

      - name: Disable node version check
        run: yarn config set ignore-engines true

      - name: Install packages marked as dependencies
        run: yarn

      - name: Build package contents
        run: yarn build
