name: Test coverage and report
on:
  # NOTE: Runs on branch to tag creation.
  create:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test-coverage-report:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell

      - name: Disable node version check
        run: yarn config set ignore-engines true

      - name: Install packages marked as dependencies
        run: yarn

      - name: Run tests
        run: yarn test:coverage:report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: .coverage/lcov.info
