name: Test
on:
  # NOTE: Runs on branch to tag creation.
  create:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: thaibault/install-npm-package-dependencies-action@main

      - name: Run tests
        run: yarn test
