name: Test coverage and report

on:
  # NOTE: Runs on branch to tag creation.
  create:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-coverage-report:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
      - uses: thaibault/test-send-coveralls-npm-package-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
